### ISSUE TITLE
OSSL_PROVIDER_load(0, "legacy") fail

### ISSUE THREAD

**Issue by studywithallofyou** [timokiller/navicat-keygen#1]
环境：windows11 openssl 3.0.3 vs2022
现象：
1. 按照步骤，编译没有问题，第一步替换公钥没有问题，生成了pem文件
2. 在第二部生成序列号的最后一步，输入完1-Premium 2-Englis 3-16之后，报了一个如下错误
[-] .\navicat-keygen\navicat_serial_generator.cpp:153 ->
    OSSL_PROVIDER_load failed.

我查了资料，在openssl的github上报过类似的错误，但是表示已经修复了，并且是2021年修复的，目前我是用的是openssl最新的版本，理论上已经包含了这个修复。

所以请帮忙调查一下原因

**Comment by timokiller** [comment]
这个问题我也遇到过，经过求助神通广大的群友，给出的答案是win11的问题，可以通过github的“Action”功能在线编译，然后下载本地使用。
